inputs:
  port:
    description: "Specify port for node application to run"
    default: 7001
  environment: 
    description: "Environment for application"
    default: "DEV"
runs:
  using: "composite"
  steps:
      working-directory: pip-dependencies
    - name: Print output
      run: echo Deployment to ${{ inputs.environment }} has started...
      shell: powershell
    - name: Install dependencies
      run: npm install
      shell: powershell
    - name: Delete service
      run: C:\\Users\\Samanta\\AppData\\Roaming\\npm\\pm2 delete "greetings-app${{ inputs.environment }}" & EXIT /B 0
      shell: powershell
    - name: Start service
      run: C:\\Users\\Samanta\\AppData\\Roaming\\npm\\pm2 start app.py --name "greetings-app-${{ inputs.environment }}" -- ${{ inputs.port }}
      shell: powershell
    