runs:
  using: "composite"
  steps:
    - name: Install pip dependencies
      run: |
        echo Installing pip ...
        C:\\Python311\\Scripts\\pip install -r requirments.txt
      shell: powershell