
name: PraktDarbs_ar_Actions

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.5.2
      #- uses: ./.github/actions/build

  install-pip-deps:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.5.2
      #- uses: ./.github/actions/build

  deploy-to-dev:
    runs-on: self-hosted
    needs: [build]
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/deploy
        with:
          port: 7001
          environment: 'DEV'

  tests-on-dev:
    runs-on: self-hosted
    needs: [deploy-to-dev]
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
          repository: 'mtararujs/course-js-api-framework'
          path: 'api-tests'
      #- uses: ./.github/actions/test
       # with:
         # environment: 'DEV'

  deploy-to-staging:
    runs-on: self-hosted
    needs: [tests-on-dev]
    steps:
      - uses: actions/checkout@v3.5.2
      #- uses: ./.github/actions/deploy
      #  with:
        #  port: 7002
         # environment: 'STG'

  tests-on-staging:
    runs-on: self-hosted
    needs: [deploy-to-staging]
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
          repository: 'mtararujs/course-js-api-framework'
          path: 'api-tests'
      #- uses: ./.github/actions/test
       # with:
        #  environment: 'STG'

  deploy-to-preprod:
    runs-on: self-hosted
    needs: [tests-on-staging]
    steps:
      - uses: actions/checkout@v3.5.2
     # - uses: ./.github/actions/deploy
       # with:
        #  port: 7003
        #  environment: 'PrePRD'

  tests-on-preprod:
    runs-on: self-hosted
    needs: [deploy-to-preprod]
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
          repository: 'mtararujs/course-js-api-framework'
          path: 'api-tests'
     # - uses: ./.github/actions/test
       # with:
        #  environment: 'PrePRD'

  deploy-to-prod:
    runs-on: self-hosted
    needs: [tests-on-preprod]
    steps:
      - uses: actions/checkout@v3.5.2
     # - uses: ./.github/actions/deploy
      #  with:
       #   port: 7004
        #  environment: 'deploy-to-prod'
                  
  tests-on-prod:
    runs-on: self-hosted
    needs: [deploy-to-prod]
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
          repository: 'mtararujs/course-js-api-framework'
          path: 'api-tests'
     # - uses: ./.github/actions/test
      #  with:
        #  environment: 'PRD'